
###
GET http://localhost:8081/catalog

###
GET http://localhost:8081/orders/199

###
GET http://localhost:8081/authors

###
POST http://localhost:8081/admin/initialize

###
POST http://localhost:8081/orders
Content-Type: application/json

{
  "items": [
    {
      "bookId": 89,
      "quantity": 1
    },
    {
      "bookId": 99,
      "quantity": 10
    }
  ],
  "recipient": {
    "name": "John Doe",
    "phone": "123-456-789",
    "street": "Cwiartki 3/4",
    "city": "Krakow",
    "zipCode": "30-150",
    "email": "johndoe@example.org"
  }
}

###
POST http://localhost:8081/users
Content-Type: application/json

{
  "username": "example@example.pl",
  "password": "passd"
}

###
// @no-redirect
POST http://localhost:8081/login
Content-Type: application/json

{
  "username": "example@example.pl",
  "password": "passd"
}

###
GET http://localhost:8081/orders/107